[build]
  publish = "public/"
  command = "hexo clean && hexo g"
  environment = {NODE_ENV = "8.10.0"}

[context.production]
  command = "hexo clean && hexo g"
  publish = "public/"

[context.deploy-preview]
  command = "hexo clean && hexo g --drafts"
  publish = "public/"

[context.branch-deploy]
  command = "hexo clean && hexo g"
  publish = "public/"
