[build]
  publish = "public/"
  command = "npm run build"
  environment = {NODE_ENV = "8.10.0"}

[[redirects]]
  from = "https://anbu-blog.netlify.com/"
  to = "https://blog.anbuchelva.in/"
  status = 301
  force = true
