[build]
  publish = "public/"
  command = "hexo clean && hexo g"
  environment = {NODE_ENV = "8.10.0"}

[context.production]
  command = "hexo clean && hexo g && npm run netlify-cms"
  publish = "public/"

[context.deploy-preview]
  command = "hexo clean && hexo g --drafts && npm run netlify-cms"
  publish = "public/"

[context.branch-deploy]
  command = "hexo clean && hexo g && npm run netlify-cms"
  publish = "public/"

[[redirects]]
  from = "/Gernal"
  to = "/general"
  status = 301
  force = false
